### ISSUE TITLE
Examples need SoundFont.Ports

### ISSUE THREAD

**Issue by rhofour** [newlandsvalley/elm-webmidi-ports#1]
When trying to play the piano and midiInstrument examples I get errors that SoundFont.Ports cannot be found. I'm assuming this refers to your other project https://github.com/newlandsvalley/elm-soundfont-ports . However, I'm not sure how I'm supposed to install this so these examples work.

Can you add something to the existing documentation to cover this?

**Comment by newlandsvalley** [comment]
It should work as advertised.  I suppose one thing I don't mention is that you can't just load the html of an example directly into a browser - you have to host it on some web server.  I use Apache on linux.  I find the simplest thing to do is to place a symbolic link to my overall elm development directory inside /var/www, browse to localhost and then just drill down to the html I want to load.

Is this the problem?

**Comment by rhofour** [comment]
Here's what happens when I try to compile the examples:
> [rofer@laptop-2017 examples]$ ./compilep.sh 
> I cannot find module 'SoundFont.Ports'.
> 
> Module 'Piano' is trying to import it.
> 
> Potential problems could be:
>   * Misspelled the module name
>   * Need to add a source directory or new dependency to elm-package.json

A similar thing happens with compilep.sh

I've got a fresh installation of elm 0.18.0 and I already compiled the main project with compile.sh. Is there something I'm missing?

**Comment by newlandsvalley** [comment]
Ah -  I see the problem.  I had included SoundFont in examples/src but had excluded it in .gitignore.  I guess I must have found the necessity of copying the code distasteful. I think I was waiting (in vain) for a resolution of the problem of not being allowed to publish packages with native dependencies.

Can you try it again?  Sorry for the pain.

**Comment by rhofour** [comment]
That fixed it, thanks!

There might be an even clear solution with a Git submodules, but I'm not sure. Either ways I'll close this.

**Comment by newlandsvalley** [comment]
Many thanks.  Yes, I remember briefly considering Git submodules - these would work, I think. My main issue was that I wanted to publish a general MIDI library but couldn't - I had to split it up into publishable and unpublishable parts.
