### ISSUE TITLE
Files aren't formatted with elm-format

### ISSUE THREAD

**Issue by rhofour** [newlandsvalley/elm-webmidi-ports#10]
Right now most of the Elm files are formatted with elm-format. Would you accept a PR to reform the Elm files?

I like autoformatters because they give me one less thing to think about when I'm writing code. However, they don't work well if everyone isn't on board as they'll otherwise clutter up unrelated changes and make the history harder to follow.

**Comment by newlandsvalley** [comment]
Definitely.  I wrote a good deal of Elm code before elm-format existed or when it had one or two annoying bugs.  But I eventually moved over to using it for the later Elm projects.  I have it in my Atom editor but I suspect it's an old version.
