### ISSUE TITLE
FR: Support MIDI output

### ISSUE THREAD

**Issue by rhofour** [newlandsvalley/elm-webmidi-ports#3]
I'm going to get to work on this.

For the first version I'm thinking something similar to how inputs are currently handled where we don't differentiate between devices so any output will be sent to every device.

**Comment by newlandsvalley** [comment]
Good! I would definitely accept a PR for this.,  I think the web-midi API is reasonably symmetrical between input and output.

**Comment by newlandsvalley** [comment]
Fixed via 8a1d1743f87674784adad81daac6e279b6968087.  Many thanks!
