### ISSUE TITLE
FR: Add the ability to distinguish between midi devices

### ISSUE THREAD

**Issue by rhofour** [newlandsvalley/elm-webmidi-ports#5]
I can probably write this, but I'm opening this to track it and hopefully get some input on how to implement this.

Input and output devices are already tracked and exposed to Elm, but right now you can't do anything with them.

For input:
I think the most straightforward thing would be to expose the ID of the midi device in the EncodedEvent and Event messages. That way clients can easily ignore it if they don't care, but they also have all the information if they want to use it. There might be a race if we receive a MIDI message followed by the device immediately disconnecting it's possible when a client sees the decoded event the attached device ID doesn't match up to any device. I don't think this is much of a problem though.

For output:
I think the simplest thing here would be to have two different send functions. One which sends to everything (like the existing one) and another which accepts a list of device ids.

Thoughts?

**Comment by newlandsvalley** [comment]
What sort of applications do you want to build with this?  When I started it, my only aim was to be able to play the MIDI keyboard that I'd just bought!

But I think you're right.  If more than one input device connects, clients will need to discriminate between them and the obvious answer is to put the device id into each message. And for output we'd need both a multiplex send and a point-to-point(s) send.  I suppose then we could build a MIDI router.

I don't think we'd need to bother too much about lost messages if a device disconnects.  It's not as if we're re-inventing MQ with guaranteed once-only delivery semantics.  We already listen to disconnections and so the sender will eventually be informed and can change his output options, with the proviso that in-transit messages will be lost.

**Comment by rhofour** [comment]
I've got two grid MIDI controllers (a Novation Launchpad Pro and a Midi Fighter) which have LEDs in them. I'm working on a program similar to Melodics (think DDR, but for MIDI controllers) where you can enter a pattern to practice, then get feedback on your timing as you do.

To make either of my controllers light up when you hit them you need to listen for their note on messages then send them back. The first problem I encountered was that my computer also has virtual MIDI Through ports that are connected to each other. So if I listen for a note on event then send it out I'll end up in a loop.

I'll probably start with adding IDs to input, then followup with another PR changing output.

**Comment by newlandsvalley** [comment]
@rhofour fixed via f0b3138194de5034d89e2998f21c2759d250de94
